### ISSUE TITLE
[BUG] Questionnaire YAML Template downloaded as JSON

### ISSUE THREAD

**Issue by cbellone** [konveyor/tackle2-ui#1515] opened 2023-11-06 14:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

99.0.0 (nightly)

### Priority

Undefined (Default)

### Current Behavior

Upon click on the "Download YAML Template" button

![image](https://github.com/konveyor/tackle2-ui/assets/3385346/79bb7f6b-b215-45b4-a970-614b9df5e289)

you can save a file named `questionnaire-template.yaml`. 

However, if you open the file you'll see that the file format is actually JSON, not YAML.
This is what I see on my disk:

```json
{
  "name": "Test questionnaire  (SAMPLE)",
  "description": "This is a sample questionnaire in YAML format",
  "required": true,
  "sections": [
    {
      "order": 1,
      "name": "Section 1",
      "questions": [
        {
          "order": 1,
          "text": "What is your favorite color?",
          "explanation": "Please select your favorite color.",
          "includeFor": [
            {
              "category": "Category1",
              "tag": "Tag1"
            }
          ],
          "excludeFor": [],
          "answers": [
            {
              "order": 1,
              "text": "Red",
              "risk": "red",
              "rationale": "Red is a nice color.",
              "mitigation": "No mitigation needed.",
              "applyTags": [],
              "autoAnswerFor": [
                {
                  "category": "Category1",
                  "tag": "Tag1"
                }
              ],
              "selected": false
            },
            {
              "order": 2,
              "text": "Blue",
              "risk": "green",
              "rationale": "Blue is a calming color.",
              "mitigation": "No mitigation needed.",
              "applyTags": [],
              "autoAnswerFor": [],
              "selected": false
            }
          ]
        },
        {
          "order": 2,
          "text": "What is your favorite sport?",
          "explanation": "Please select your favorite sport.",
          "excludeFor": [
            {
              "category": "Category1",
              "tag": "Tag1"
            }
          ],
          "answers": [
            {
              "order": 1,
              "text": "Soccer",
              "risk": "red",
              "rationale": "There are other sports?",
              "mitigation": "Beware of crunching tackles. High risk of injury.",
              "applyTags": [],
              "autoAnswerFor": [],
              "selected": false
            },
            {
              "order": 2,
              "text": "Cycling",
              "risk": "red",
              "rationale": "Correct.",
              "mitigation": "High risk of decapitation by car.",
              "applyTags": [],
              "autoAnswerFor": [],
              "selected": false
            },
            {
              "order": 3,
              "text": "Climbing",
              "risk": "yellow",
              "rationale": "Climbing is fun.",
              "mitigation": "Slight bit of mitigation needed.",
              "applyTags": [],
              "autoAnswerFor": [],
              "selected": false
            },
            {
              "order": 4,
              "text": "Swimming",
              "risk": "yellow",
              "rationale": "Swimming is fun, too.",
              "mitigation": "Slight bit of mitigation needed. Drowning can be a problem.",
              "applyTags": [],
              "autoAnswerFor": [],
              "selected": false
            },
            {
              "order": 5,
              "text": "Running",
              "risk": "red",
              "rationale": "Oof.",
              "mitigation": "Some mitigation required. High risk of injury. Don't run with scissors (or at all).",
              "applyTags": [],
              "autoAnswerFor": [],
              "selected": false
            }
          ]
        },
        {
          "order": 3,
          "text": "What is your favorite shape?",
          "explanation": "Please select your favorite shape.",
          "includeFor": [
            {
              "category": "Category1",
              "tag": "Tag1"
            }
          ],
          "excludeFor": [],
          "answers": [
            {
              "order": 1,
              "text": "Circle",
              "risk": "red",
              "selected": false
            },
            {
              "order": 2,
              "text": "Square",
              "risk": "green",
              "selected": false
            }
          ]
        }
      ]
    }
  ],
  "thresholds": {
    "red": 5,
    "yellow": 10,
    "unknown": 15
  },
  "riskMessages": {
    "red": "High risk",
    "yellow": "Medium risk",
    "green": "Low risk",
    "unknown": "Unknown risk"
  }
}
```

### Expected Behavior

File content should be in YAML format

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Open the "Administration" view and choose "Assessment Questionnaire"
2. Click on "Download YAML Template"
3. Save the file locally
4. Open the file with a text editor

### Environment

```markdown
- OS: Mac OS 14.0
- Browser: Firefox 119.0
```

### Anything else?

When I try to upload the downloaded JSON file, it works without problems.
I personally don't mind configuring the questionnaire using a JSON descriptor, I just wanted to point it out because it might be confusing for other people

**Comment by sjd78** [comment] 2023-12-14 19:15
Duplicate of https://issues.redhat.com/browse/MTA-1720
Resolved by https://github.com/konveyor/tackle2-ui/pull/1574

**Closed by sjd78** 2023-12-14 19:15 UTC
Labels: kind/bug, needs-triage
