### ISSUE TITLE
Error when trying to export applications as issues to tracker

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#952] opened 2023-05-31 00:01 UTC
{"error":"UNIQUE constraint failed: Ticket.ApplicationID, Ticket.TrackerID"}

**Comment by ibolton336** [comment] 2023-05-31 00:04
<img width="716" alt="Screenshot 2023-05-30 at 8 03 23 PM" src="https://github.com/konveyor/tackle2-ui/assets/11218376/d1c9b6dc-9039-4064-b257-cdb614eef49e">
<img width="1236" alt="Screenshot 2023-05-30 at 8 04 00 PM" src="https://github.com/konveyor/tackle2-ui/assets/11218376/0461dfde-cf35-4c29-ab1b-9ad97c4e3574">
<img width="673" alt="Screenshot 2023-05-30 at 8 04 35 PM" src="https://github.com/konveyor/tackle2-ui/assets/11218376/7c5e08f7-599a-4c11-b778-b757d758fccc">

**Comment by gildub** [comment] 2023-05-31 10:39
To reproduce:

1. Remove application(s) from migration waves
2. Re-add application(s) then re-export to Jira instance

The conflict occurs because the ticket(s) already exist.

Currently when an application is removed from a migration waves the UI doesn't delete the ticket.
Because deleting a ticket in the Hub doesn't delete the ticket in Jira. 
Effectively a Jira ticket has to be removed manually from Jira.
So we need to confirm if that's the expected behavior or if we have to delete the ticket in the Hub.

**Comment by mansam** [comment] 2023-05-31 13:53
In the Hub the ticket resources are attached to the application rather than the wave, so it should be possible for the UI to find the preexisting ticket and avoid the 409 Conflict generated by the Hub. I could add a field on the Application resource for the Ticket ref to make it more visible. But that would still leave the question of what to do with stray tickets left in Jira.  It doesn't look like the enhancements covered removing tickets from Jira at all. It seems reasonable to me that if an Application is removed from a Migration Wave (or the Migration Wave is removed), then the tickets should be removed from Jira as well. @rromannissen does that make sense to you, or is there another way you'd prefer us to handle deleting tickets from Jira?

**Comment by ibolton336** [comment] 2023-05-31 20:37
@rromannissen 

If we attempt to create an issue and the issue fails to create with a healthy status: 
-  issue/app already existing
-  an underlying issue with the tracker causing the issue creation to fail. I have seen this when creating an issue against a tracker/instance that is using http instead of https

Then, what should the user see? 

Should we leave the issue with error state in the migration wave? Seems like this is our only option since the issues are permanently created in JIRA? @mansam Could we have a special case where we can delete the issue from the tracker via the UI if this is the case? What would the user action look like for this - maybe we should automatically remove the issue/application from the instance after showing a notification that the issue creation has failed?

**Comment by mansam** [comment] 2023-05-31 21:40
@ibolton336 

The hub will only let one representation of a ticket be created per app, per tracker. In the case where an issue fails to be created due to some error (http instead of https, invalid issue type or project, etc), fixing that will cause the issue to be created on the Jira side. 

Tickets in the Hub belong to the Application and Tracker rather than the Migration Wave, so the scenario where an Application is removed from one wave and assigned to another later should work as is.

**Comment by gildub** [comment] 2023-06-01 12:49
@rromannissen , going back to re-export applications that already have tickets worked and still works, the difference being the foreign key error message surfaces in the notification.

We can trap those errors and notify the user about exiting tickets.

**Comment by gildub** [comment] 2023-06-01 12:59
| May require some fine tuning if a user has multiple trackers & is fetching loads of tickets from different places. 

@ibolton336, I believe an application can have only one tickets attached to it.

Also as @rromannissen mentioned when an application is moved away from a migration wave to a new one we need to be able to remove the application then to re-export it. So we cannot filter out application which already have a ticket otherwise we'll end up with orphans on tackle side.

**Comment by ibolton336** [comment] 2023-06-01 13:03
@gildub Makes sense. If the application is removed from a wave, then it should be able to be reassigned. Until then (while it is still assigned to a wave), it should not be able to be re-exported.

**Comment by ibolton336** [comment] 2023-06-01 13:10
>@ibolton336, I believe an application can have only one ticket attached to it.

But what if an application with the same ID is assigned to a ticket on different trackers. Then we need to check if the app IDs are the same AND the tracker IDs are the same before blocking the user from exporting a duplicate application/ticket to a tracker.

**Comment by gildub** [comment] 2023-06-01 13:38
@ibolton336, 

It seems the Hub's API doesn't allow more than one ticket by application, @mansam please correct me if needed.

If an application is assigned to a migration wave then it cannot be used by another migration wave therefore it cannot be re-exported.

**Comment by mansam** [comment] 2023-06-01 13:45
The Hub's API allows an application to have one ticket max per tracker (so it could theoretically be exported to multiple different Jira instances, but only one ticket could be created per instance), and an application can be assigned to only one wave at a time. The tickets are not linked to the migration wave at all. You can use the hub API to remove the application from one migration wave and add it to another. The tickets will remain valid.

**Comment by gildub** [comment] 2023-06-01 16:55
Thanks @mansam for clarifying.

So even if technically on the Hub side an application can have multiple `/tickets`, each for a distinct `/tracker` then in practice that cannot happen as an application can only be assigned to one migration wave.

**Comment by ibolton336** [comment] 2023-06-02 14:06
Opened #970 to resolve this as discussed in yesterdays meeting.

**Closed** 2023-06-06 13:26 UTC
Labels: triage/accepted
